applicationName: OauthTemplateApp
local-config-override-folder: ${user.home}/apps/${applicationName}
spring:
  application:
    name: ${applicationName}
  config:
    import:
      - classpath:config/security/GoogleOauth2.yml
      - classpath:config/security/GithubOauth2.yml
      - classpath:config/db/hikari.yml
      - classpath:config/monitoring/actuator.yml
      - optional:file:${local-config-override-folder}/secrets.properties
      - optional:file:${local-config-override-folder}/env_overrides.properties

app:
  security:
    password:
      pwned-passwords:
        enabled: true
        base-url: https://api.pwnedpasswords.com

#logging:
  #level:
  #  org.springframework.security: TRACE
